# Generated by Django 2.1.7 on 2019-08-21 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_auto_20190821_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
